version: "3.8"

services:
  php:
    image: php:8.1-apache
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: bash -c "composer install && apache2-foreground"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app
    command: install

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laragon_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
